apiVersion: v1
kind: ServiceAccount
metadata:
  name: garage-codefresh-admin
  labels:
    {{- include "garage.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: garage-codefresh-admin
  annotations:
    kubernetes.io/service-account.name: garage-codefresh-admin
type: kubernetes.io/service-account-token